name: moodle-docker CI

on: [push, pull_request]

jobs:
  integration:
    name: Integration checks
    runs-on: ubuntu-22.04

    steps:
      - name: Checking out moodle-docker
        uses: actions/checkout@v4

      - name: Checking out moodle
        uses: actions/checkout@v4
        with:
          repository: moodle/moodle
          path: moodle
          ref: ${{ matrix.branch }}

      - name: Prepare moodle-docker environment
        run: |
          cp config.docker-template.php moodle/config.php
          tests/integration-setup.sh

      - name: Run moodle-docker tests
        run: |
          tests/integration-test.sh

      - name: Stop moodle-docker
        run: |
          tests/integration-teardown.sh

  PHPUnit:
    needs: integration
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          # PostgreSQL (highest, lowest php supported)
          - { branch: main,              php: "8.3", database: pgsql, suite: phpunit-full } # Full run only for main.

    steps:
      - name: Checking out moodle-docker
        uses: actions/checkout@v4

      - name: Checking out moodle
        uses: actions/checkout@v4
        with:
          repository: moodle/moodle
          path: moodle
          ref: ${{ matrix.branch }}

      - name: Prepare moodle-docker environment
        run: |
          cp config.docker-template.php moodle/config.php
          export MOODLE_DOCKER_DB="${{ matrix.database }}"
          export MOODLE_DOCKER_PHP_VERSION="${{ matrix.php }}"
          export SUITE="${{ matrix.suite }}"
          tests/phpunit-setup.sh

      - name: Run moodle-docker tests
        run: |
          export MOODLE_DOCKER_DB="${{ matrix.database }}"
          export SUITE="${{ matrix.suite }}"
          tests/phpunit-test.sh

      - name: Stop moodle-docker
        run: |
          export MOODLE_DOCKER_DB="${{ matrix.database }}"
          export SUITE="${{ matrix.suite }}"
          tests/phpunit-teardown.sh

  Behat:
    needs: integration
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          # PostgreSQL (highest, lowest php supported)
          - { branch: main,              php: "8.3", database: pgsql, browser: chrome,  suite: behat }

    steps:
      - name: Checking out moodle-docker
        uses: actions/checkout@v4

      - name: Checking out moodle
        uses: actions/checkout@v4
        with:
          repository: moodle/moodle
          path: moodle
          ref: ${{ matrix.branch }}

      - name: Prepare moodle-docker environment
        run: |
          cp config.docker-template.php moodle/config.php
          export MOODLE_DOCKER_DB="${{ matrix.database }}"
          export MOODLE_DOCKER_PHP_VERSION="${{ matrix.php }}"
          export SUITE="${{ matrix.suite }}"
          export MOODLE_DOCKER_BROWSER="${{ matrix.browser }}"
          tests/behat-setup.sh

      - name: Run moodle-docker tests
        run: |
          export MOODLE_DOCKER_DB="${{ matrix.database }}"
          export SUITE="${{ matrix.suite }}"
          tests/behat-test.sh

      - name: Stop moodle-docker
        run: |
          export MOODLE_DOCKER_DB="${{ matrix.database }}"
          export SUITE="${{ matrix.suite }}"
          tests/behat-teardown.sh

  App:
    needs: integration
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          # PostgreSQL (highest, lowest php supported)
          # First tests are for app developers.
          - { branch: MOODLE_403_STABLE, php: "8.2", suite: app-development, app-version: "latest" }

    steps:
      - name: Checking out moodle-docker
        uses: actions/checkout@v4

      - name: Checking out moodle
        uses: actions/checkout@v4
        with:
          repository: moodle/moodle
          path: moodle
          ref: ${{ matrix.branch }}

      - name: Prepare moodle-docker environment
        run: |
          cp config.docker-template.php moodle/config.php
          export MOODLE_DOCKER_PHP_VERSION="${{ matrix.php }}"
          export SUITE="${{ matrix.suite }}"
          export MOODLE_DOCKER_APP_VERSION="${{ matrix.app-version }}"
          tests/app-setup.sh

      - name: Run moodle-docker tests
        run: |
          export MOODLE_DOCKER_APP_VERSION="${{ matrix.app-version }}"
          export SUITE="${{ matrix.suite }}"
          tests/app-test.sh

      - name: Stop moodle-docker
        run: |
          export SUITE="${{ matrix.suite }}"
          export MOODLE_DOCKER_APP_VERSION="${{ matrix.app-version }}"
          tests/app-teardown.sh
